//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Build_Table
    {
        public decimal RecordNumber { get; set; }
        public string BuildNo { get; set; }
        public string PartNo { get; set; }
        public string Loc { get; set; }
        public string Desr { get; set; }
        public string Ex { get; set; }
        public string Variant { get; set; }
        public string Ind { get; set; }
    }
}
