//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drain_Data
    {
        public int RecordNumber { get; set; }
        public string DefectType_1 { get; set; }
        public string DefectType_2 { get; set; }
        public string DefectType_3 { get; set; }
        public string DefectType_4 { get; set; }
        public string DefectType_5 { get; set; }
        public string DefectType_6 { get; set; }
        public string DefectType_7 { get; set; }
        public string DefectType_8 { get; set; }
        public string DefectType_9 { get; set; }
        public string DefectType_10 { get; set; }
        public string DefectCatagory_1 { get; set; }
        public string DefectCatagory_2 { get; set; }
        public string DefectCatagory_3 { get; set; }
        public string DefectCatagory_4 { get; set; }
        public string DefectCatagory_5 { get; set; }
        public string DefectCatagory_6 { get; set; }
        public string DefectCatagory_7 { get; set; }
        public string DefectCatagory_8 { get; set; }
        public string DefectCatagory_9 { get; set; }
        public string DefectCatagory_10 { get; set; }
        public Nullable<int> X_Coordinate_1 { get; set; }
        public Nullable<int> X_Coordinate_2 { get; set; }
        public Nullable<int> X_Coordinate_3 { get; set; }
        public Nullable<int> X_Coordinate_4 { get; set; }
        public Nullable<int> X_Coordinate_5 { get; set; }
        public Nullable<int> X_Coordinate_6 { get; set; }
        public Nullable<int> X_Coordinate_7 { get; set; }
        public Nullable<int> X_Coordinate_8 { get; set; }
        public Nullable<int> X_Coordinate_9 { get; set; }
        public Nullable<int> X_Coordinate_10 { get; set; }
        public Nullable<int> Y_Coordinate_1 { get; set; }
        public Nullable<int> Y_Coordinate_2 { get; set; }
        public Nullable<int> Y_Coordinate_3 { get; set; }
        public Nullable<int> Y_Coordinate_4 { get; set; }
        public Nullable<int> Y_Coordinate_5 { get; set; }
        public Nullable<int> Y_Coordinate_6 { get; set; }
        public Nullable<int> Y_Coordinate_7 { get; set; }
        public Nullable<int> Y_Coordinate_8 { get; set; }
        public Nullable<int> Y_Coordinate_9 { get; set; }
        public Nullable<int> Y_Coordinate_10 { get; set; }
    }
}
