//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HA_66a_LabelData
    {
        public int RecordNo { get; set; }
        public string ChassisNo { get; set; }
        public string FRAMESEQUENCENO { get; set; }
        public string PARTNO { get; set; }
        public string PARTQTY { get; set; }
        public string BILLOFMATERIALLINETXT { get; set; }
    }
}
