//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lable_Data
    {
        public decimal RecordNumber { get; set; }
        public string Location { get; set; }
        public string ChassisNo { get; set; }
        public string SequenceNo { get; set; }
        public string TankNo { get; set; }
        public string PartNo_1 { get; set; }
        public string PartNo_2 { get; set; }
        public string PartNo_3 { get; set; }
        public string PartNo_4 { get; set; }
        public string PartNo_5 { get; set; }
        public string PartNo_6 { get; set; }
        public string PartNo_7 { get; set; }
        public string PartNo_8 { get; set; }
        public string PartNo_9 { get; set; }
        public string PartNo2_1 { get; set; }
        public string PartNo2_2 { get; set; }
        public string PartNo2_3 { get; set; }
        public string PartNo2_4 { get; set; }
        public string PartNo2_5 { get; set; }
        public string PartNo2_6 { get; set; }
        public string PartNo2_7 { get; set; }
        public string PartNo2_8 { get; set; }
        public string PartNo2_9 { get; set; }
        public string SpecialMessage1 { get; set; }
        public string SpecialMessage2 { get; set; }
    }
}
