//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TankTransaction_Data
    {
        public int RecordNumber { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string TankNumber { get; set; }
        public string SequenceNumber { get; set; }
        public string Operator { get; set; }
        public string Robot { get; set; }
        public Nullable<int> TankSize { get; set; }
        public Nullable<int> StationNumber { get; set; }
        public string DrainLocation { get; set; }
        public Nullable<int> RepairTotal { get; set; }
        public Nullable<int> ScrapTotal { get; set; }
        public Nullable<int> LeakerTotal { get; set; }
        public Nullable<int> ScratchTotal { get; set; }
        public Nullable<int> Repairs_Total { get; set; }
    }
}
