//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToughTruckStartView
    {
        public string PartNumber { get; set; }
        public string Description { get; set; }
        public string pl { get; set; }
        public Nullable<decimal> QTYOnHand { get; set; }
        public Nullable<decimal> QTYOnOrder { get; set; }
        public Nullable<decimal> TotalREQ { get; set; }
        public Nullable<decimal> TQTY { get; set; }
        public string STL_CLS { get; set; }
        public string SR_TY { get; set; }
        public string iclass { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public string seq { get; set; }
        public string chassis { get; set; }
        public string bmcd { get; set; }
        public string suppl { get; set; }
    }
}
