//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_EXT_RESOURCE_ChassisInProcess
    {
        public string ChassisNo { get; set; }
        public string FrameSequenceNo { get; set; }
        public string CabSequenceNo { get; set; }
        public string Major_Component { get; set; }
        public string Line_Location { get; set; }
        public string Location_Name { get; set; }
        public Nullable<int> Location_Number { get; set; }
        public string MajorComponentTypeCd { get; set; }
        public int AssemblyLineNo { get; set; }
        public int AssemblyLineLocationNo { get; set; }
    }
}
