//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FTBuildTableImport
    {
        public string ChassisNo { get; set; }
        public string FrameSequenceNo { get; set; }
        public string BuildStationNo { get; set; }
        public string BillOfMaterialCd { get; set; }
        public string BillOfMaterialLineCd { get; set; }
        public string BillOfMaterialLineTxt { get; set; }
        public string BillOfMaterialLineTypeCd { get; set; }
        public string PARTNO { get; set; }
        public Nullable<int> PARTQTY { get; set; }
    }
}
