//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_tbChassisBillOfMaterials
    {
        public string BillOfMaterialCd { get; set; }
        public string PARTNO { get; set; }
    }
}
