//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebTrapAlert
    {
        public int index_ { get; set; }
        public string Sequence { get; set; }
        public byte[] AlertTime { get; set; }
        public string Area { get; set; }
    }
}
